### ISSUE TITLE
ModuleName Attribute not working in 2.3.0

### ISSUE THREAD

**Issue by joshuamelcon** [Saltarelle/SaltarelleCompiler#232]
This used to work, but has recently stopped working.  I don't know if I was getting lucky before or what.  I tracked it down into NRefactory having an ErrorResolveResult about ModuleNameAttribute in MetadataUtils.GetModuleName(IAssembly) preventing the following code from determining what assembly the type is in.  I need help to resolve it further.... Here is how to reproduce:

Thanks,

file1.cs

``` csharp
using System;
using System.Collections.Generic;
using System.Text;


using System.Runtime.CompilerServices;

[assembly: ModuleName("SystemJs.js")]
[assembly: AsyncModuleAttribute]

namespace System
    {

    public class NotImplementedException : Exception
        {
        public NotImplementedException()
            {

            }
        public NotImplementedException(string s)
            {

            }
        }

    }
```

file2.cs

``` csharp

public class TestClass
    {
    public void Method()
        {
        throw new System.NotImplementedException();
        }
    }
```

``` bat
sc file1.cs /r:C:\all\SaltarelleCompiler\Runtime\CoreLib\bin\mscorlib.dll
sc file2.cs /r:C:\all\SaltarelleCompiler\Runtime\CoreLib\bin\mscorlib.dll /r:file1.dll

```

produces:

```

C:\brokenExample>sc file1.cs /r:C:\all\SaltarelleCompiler\Runtime\CoreLib\bin\mscorlib.dll 

C:\brokenExample>sc file2.cs /r:C:\all\SaltarelleCompiler\Runtime\CoreLib\bin\mscorlib.dll /r:file1.dll 
(0,0): error CS7999: INTERNAL ERROR: System.Exception: When processing System.NotImplementedException ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Saltarelle.Compiler.AttributeReader.ChangeType(Object source, Type type)
   at Saltarelle.Compiler.AttributeReader.ReadAttribute[TAttribute](IAttribute attr)
   at Saltarelle.Compiler.AttributeReader.ReadAttribute[TAttribute](IEnumerable`1 attributes)
   at CoreLib.Plugin.MetadataUtils.GetModuleName(IAssembly assembly)
   at CoreLib.Plugin.MetadataUtils.GetModuleName(ITypeDefinition type)
   at CoreLib.Plugin.Linker.ImportVisitor.GetTypeModuleName(ITypeDefinition type)
   --- End of inner exception stack trace ---
   at CoreLib.Plugin.Linker.ImportVisitor.GetTypeModuleName(ITypeDefinition type)
   at CoreLib.Plugin.Linker.ImportVisitor.VisitTypeReferenceExpression(JsTypeReferenceExpression expression, Object data)
   at Saltarelle.Compiler.JSModel.Expressions.JsTypeReferenceExpression.Accept[TReturn,TData](IExpressionVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitExpression(JsExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitNewExpression(JsNewExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.Expressions.JsNewExpression.Accept[TReturn,TData](IExpressionVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitExpression(JsExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitThrowStatement(JsThrowStatement statement, TData data)
   at Saltarelle.Compiler.JSModel.Statements.JsThrowStatement.Accept[TReturn,TData](IStatementVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitStatement(JsStatement statement, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.<>c__DisplayClassf.<VisitStatements>b__e(JsStatement s)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.<>c__DisplayClass6`1.<VisitCollection>b__5(T x, Int32 _)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitCollection[T](IList`1 orig, Func`3 visitor)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitCollection[T](IList`1 orig, Func`2 visitor)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitStatements(IList`1 statements, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitBlockStatement(JsBlockStatement statement, TData data)
   at Saltarelle.Compiler.JSModel.Statements.JsBlockStatement.Accept[TReturn,TData](IStatementVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitStatement(JsStatement statement, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitFunctionDefinitionExpression(JsFunctionDefinitionExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.Expressions.JsFunctionDefinitionExpression.Accept[TReturn,TData](IExpressionVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitExpression(JsExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitObjectLiteralProperty(JsObjectLiteralProperty value, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.<>c__DisplayClassc.<VisitObjectLiteralProperties>b__b(JsObjectLiteralProperty v)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.<>c__DisplayClass3`1.<VisitCollection>b__2(T x, Int32 _)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitCollection[T](IList`1 orig, Func`3 visitor)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitCollection[T](IList`1 orig, Func`2 visitor)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitObjectLiteralProperties(IList`1 values, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitObjectLiteralExpression(JsObjectLiteralExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.Expressions.JsObjectLiteralExpression.Accept[TReturn,TData](IExpressionVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitExpression(JsExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.<>c__DisplayClass9.<VisitExpressions>b__8(JsExpression expr)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.<>c__DisplayClass3`1.<VisitCollection>b__2(T x, Int32 _)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitCollection[T](IList`1 orig, Func`3 visitor)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitCollection[T](IList`1 orig, Func`2 visitor)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitExpressions(IList`1 expressions, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitInvocationExpression(JsInvocationExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.Expressions.JsInvocationExpression.Accept[TReturn,TData](IExpressionVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitExpression(JsExpression expression, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitExpressionStatement(JsExpressionStatement statement, TData data)
   at Saltarelle.Compiler.JSModel.Statements.JsExpressionStatement.Accept[TReturn,TData](IStatementVisitor`2 visitor, TData data)
   at Saltarelle.Compiler.JSModel.RewriterVisitorBase`1.VisitStatement(JsStatement statement, TData data)
   at CoreLib.Plugin.Linker.ImportVisitor.<>c__DisplayClassf.<Process>b__2(JsStatement s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CoreLib.Plugin.Linker.ImportVisitor.Process(IMetadataImporter metadataImporter, INamer namer, ICompilation compilation, IList`1 statements)
   at CoreLib.Plugin.Linker.Process(IList`1 statements)
   at Saltarelle.Compiler.Driver.CompilerDriver.Compile(CompilerOptions options). Please report this as an issue on https://github.com/erik-kallen/SaltarelleCompiler/
```
