### ISSUE TITLE
Referencing assemblies compiled against .NET Framework not working in 2.3.1

### ISSUE THREAD

**Issue by mpeschka** [Saltarelle/SaltarelleCompiler#240]
I have several projects that reference an assembly of skeleton DTO classes. These assemblies are compiled with csc.exe using the .NET Framework 2.0, and are then included as references in my Saltarelle projects. This arrangement has been working for some time, but when I updated to Saltarelle 2.3.1 (I never tried 2.3.0, so I can't comment there), it stopped working. The issue seems to be caused by the various assembly attributes added by csc.exe during compilation. I suspect this is related/similar to the problem reported in #232.

I'd be happy to provide any further information, or work on a different reproduction scenario if needed.

Thanks!

To reproduce:

file1.cs:

```
namespace SaltarelleTest
{
    public class TestClass
    {
        public TestClass()
        {
        }
    }
}
```

file2.cs:

```
public class TestScript
{
    public void Method()
    {
        var x = new SaltarelleTest.TestClass();
        if (x != null) x = null;
    }
}
```

To build:

```
%windir%\Microsoft.NET\Framework\v2.0.50727\csc /target:library file1.cs
%saltarelle%\sc file2.cs /r:%saltarelle%\mscorlib.dll /r:file1.dll
```

Produces an exception such as:

```
(0,0): error CS7999: INTERNAL ERROR: System.TypeLoadException: Type 'System.Runtime.CompilerServices.CompilationRelaxationsAttribute' not found in assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a4048e8fcc593f14'
   at IKVM.Reflection.Universe.GetMissingTypeOrThrow(Module requester, Module module, Type declaringType, TypeName typeName)
   at IKVM.Reflection.Assembly.ResolveType(Module requester, TypeName typeName)
   at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context)
   at IKVM.Reflection.Reader.ModuleReader.GetMemberRef(Int32 index, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at IKVM.Reflection.Reader.ModuleReader.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at IKVM.Reflection.CustomAttributeData.get_Constructor()
   at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.AddCustomAttributes(IEnumerable`1 attributes, ICollection`1 targetCollection)
   at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.AddAttributes(Assembly assembly, IList`1 outputList)
   at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.LoadAssembly(Assembly assembly)
   at Saltarelle.Compiler.Driver.CompilerDriver.<LoadReferences>b__29(Assembly asm)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Saltarelle.Compiler.Driver.CompilerDriver.LoadReferences(IEnumerable`1 references, IErrorReporter er)
   at Saltarelle.Compiler.Driver.CompilerDriver.Compile(CompilerOptions options)
. Please report this as an issue on https://github.com/erik-kallen/SaltarelleCompiler/
```

Through reflection, I see that csc.exe has added two attributes:

```
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows=true)]
```

Assemblies built using Visual Studio 2012 add an additional attribute, which causes a similar TypeLoadException:

```
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
```
